name: stuartcampbell
favicon: null
layout_spectrum: 0.0319030680693686
typography_spectrum: 0.8741919063031673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.10622760001569986
  lightness: 0.13658344163559377
  saturation: 0.7819252880290151
  rhythmicContrast: 0.0875727953389287
purpose: []
